import becado
import nomina
import tipoNomina
import carga_familiar #Carga Familiar
import clasPer
import tipoEmp
import gradoInstruccion
import grupoSanguineo
import sedes
import areas
import tipo_beca
import novedades
import proceso_seleccion
import seleccion
import solicitudes
import contrato
import evaluacion
import proceso_nomina
import status
import calculo_nomina
import banco
import nivel_edu
import institucion_edu
import ejes
import nomina_becados
import nomina_becado_individual
import archivos_nominas
import wizard_lista_becados
import contacto
